"""add ai_logs table

Revision ID: 6205ef34447b
Revises: a3f8b2d41e57
Create Date: 2026-02-08 13:31:09.599798
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6205ef34447b'
down_revision: Union[str, None] = 'a3f8b2d41e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('request_messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('tokens_total', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_logs_agent_name', 'ai_logs', ['agent_name'], unique=False)
    op.create_index('ix_ai_logs_created_at', 'ai_logs', ['created_at'], unique=False)
    op.create_index('ix_ai_logs_user_id', 'ai_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_logs_user_id', table_name='ai_logs')
    op.drop_index('ix_ai_logs_created_at', table_name='ai_logs')
    op.drop_index('ix_ai_logs_agent_name', table_name='ai_logs')
    op.drop_table('ai_logs')
    # ### end Alembic commands ###
