"""add_user_action_logs_table

Revision ID: 740ca8a3eb9a
Revises: 6205ef34447b
Create Date: 2026-02-08 14:36:48.938178
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740ca8a3eb9a'
down_revision: Union[str, None] = '6205ef34447b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_action_logs_action', 'user_action_logs', ['action'], unique=False)
    op.create_index('ix_user_action_logs_created_at', 'user_action_logs', ['created_at'], unique=False)
    op.create_index('ix_user_action_logs_user_id', 'user_action_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_action_logs_user_id', table_name='user_action_logs')
    op.drop_index('ix_user_action_logs_created_at', table_name='user_action_logs')
    op.drop_index('ix_user_action_logs_action', table_name='user_action_logs')
    op.drop_table('user_action_logs')
    # ### end Alembic commands ###
